<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.11.2 on win32)" generated="20230511 18:36:29.677" rpa="false" schemaversion="3">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="DataDrivenTestingWithExcel" source="C:\Users\Ravi Singavarapu\PycharmProjects\RobotFrameWorkProject\TestCasesRB\DataDrivenTestingWithExcel.robot">
<kw name="open my browser" library="DataDrivenResources" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20230511 18:36:30.277" level="INFO">Opening browser 'Chrome' to base url 'https://the-internet.herokuapp.com/'.</msg>
<status status="PASS" starttime="20230511 18:36:30.274" endtime="20230511 18:36:36.002"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20230511 18:36:36.002" endtime="20230511 18:36:36.138"/>
</kw>
<status status="PASS" starttime="20230511 18:36:30.270" endtime="20230511 18:36:36.138"/>
</kw>
<test id="s1-s1-t1" name="loginwithexcel using ${username}" line="9">
<kw name="Invalid Login">
<arg>and</arg>
<arg>${password}</arg>
<msg timestamp="20230511 18:36:36.140" level="FAIL">Variable '${password}' not found.</msg>
<status status="FAIL" starttime="20230511 18:36:36.140" endtime="20230511 18:36:36.141"/>
</kw>
<status status="FAIL" starttime="20230511 18:36:36.139" endtime="20230511 18:36:36.142">Variable '${password}' not found.</status>
</test>
<kw name="Close browsers" library="DataDrivenResources" type="TEARDOWN">
<kw name="Close All Browsers" library="SeleniumLibrary">
<doc>Closes all open browsers and resets the browser cache.</doc>
<status status="PASS" starttime="20230511 18:36:36.143" endtime="20230511 18:36:42.419"/>
</kw>
<status status="PASS" starttime="20230511 18:36:36.143" endtime="20230511 18:36:42.420"/>
</kw>
<status status="FAIL" starttime="20230511 18:36:29.723" endtime="20230511 18:36:42.420"/>
</suite>
<status status="FAIL" starttime="20230511 18:36:29.693" endtime="20230511 18:36:42.421"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="DataDrivenTestingWithExcel">Suites.DataDrivenTestingWithExcel</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230511 18:36:30.267" level="ERROR">Error in file 'C:\Users\Ravi Singavarapu\PycharmProjects\RobotFrameWorkProject\TestCasesRB\DataDrivenTestingWithExcel.robot' on line 4: Importing library 'DataDriver' failed: ModuleNotFoundError: No module named 'DataDriver'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311\Scripts\robot.exe
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311\python311.zip
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311\DLLs
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311\Lib
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311
  C:\Users\Ravi Singavarapu\AppData\Local\Programs\Python\Python311\Lib\site-packages</msg>
</errors>
</robot>
